# Generated by Django 4.2.16 on 2024-11-06 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_remove_product_brand_brand_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalogue.brand'),
            preserve_default=False,
        ),
    ]
