# Generated by Django 4.2.16 on 2024-11-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_remove_brand_image_brand_banner_brand_featured_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='slug',
            new_name='brand_slug',
        ),
    ]
