# Generated by Django 4.2.16 on 2024-11-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_siteinfo_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedialink',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='social_media_logos/'),
        ),
    ]
