# Generated by Django 4.2.16 on 2024-11-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='platform_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
