# Generated by Django 4.2.16 on 2024-11-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_socialmedialink_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedialink',
            name='logo',
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='media_logo_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
