# Generated by Django 4.2.16 on 2024-11-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_remove_socialmedialink_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='media_logo_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
