# Generated by Django 4.2.16 on 2024-11-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_socialmedialink_media_logo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='baner1_image',
            field=models.ImageField(blank=True, null=True, upload_to='baner_image/'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='baner2_image',
            field=models.ImageField(blank=True, null=True, upload_to='baner_image/'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='baner3_image',
            field=models.ImageField(blank=True, null=True, upload_to='baner_image/'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='baner4_image',
            field=models.ImageField(blank=True, null=True, upload_to='baner_image/'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='site_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='whatsapp_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
