# Generated by Django 4.2.16 on 2024-11-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_siteinfo_baner1_image_siteinfo_baner2_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='brand_baner_image',
            field=models.ImageField(blank=True, null=True, upload_to='baner_image/'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='category_baner_image',
            field=models.ImageField(blank=True, null=True, upload_to='baner_image/'),
        ),
    ]
