# Generated by Django 4.2.16 on 2024-11-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_siteinfo_brand_baner_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='whatsapp_link',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
