# Generated by Django 4.2.16 on 2024-11-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_remove_siteinfo_whatsapp_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_line', models.CharField(blank=True, max_length=250, null=True)),
                ('tag_link', models.URLField(blank=True, null=True)),
                ('tag_percentage', models.IntegerField(blank=True, null=True)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='settings.siteinfo')),
            ],
        ),
        migrations.CreateModel(
            name='MenuName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_names', to='settings.siteinfo')),
            ],
        ),
    ]
