# Generated by Django 4.2.16 on 2024-10-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_brand_alter_product_options_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_created'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
