# Generated by Django 4.2.16 on 2024-11-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_alter_brand_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
