# Generated by Django 4.2.16 on 2024-11-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_remove_product_brand_productbrand_product_brands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='image',
        ),
        migrations.AddField(
            model_name='brand',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='brands/banners'),
        ),
        migrations.AddField(
            model_name='brand',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/featured_images'),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/logos'),
        ),
    ]
