# Generated by Django 4.2.16 on 2024-11-13 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_rename_slug_brand_brand_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='description',
            new_name='about',
        ),
    ]
